### PR TITLE
Cleanup and a few optimizations

### PR DESCRIPTION
**Pull request by CreamyCookie**
1. Methods and attributes that were referenced multiple times were replaced by a local variable.
2. Removed unnecessary initializations.
3. Made `gradiens$D` tuples instead of lists to save memory. (and renamed them as they're constants)
4. Cleaned up the code in a few places (removed unneeded brackets and docstrings now follow PEP8)
5. Renamed variables to use underscores (PEP8)
6. Made extrapolate methods more efficient by using Python's ability to access a range of a sequence.
7. Replaced fastFloor with real floor which is actually much faster.

### CODE REVIEW

**Comment by lmas** [comment]
Wow, what a massive PR, thanks man! :+1:
Gimme a couple of days to review/test it and I'll pull it in.

**Comment by lmas** [comment]
Added some test, but it fails on your code on python2:

```
Traceback (most recent call last):
  File "/home/lmas/code/opensimplex/tests/test_opensimplex.py", line 21, in test_samples
    actual = simplex.noise2d(s[0], s[1])
  File "/home/lmas/code/opensimplex/opensimplex/opensimplex.py", line 169, in noise2d
    value += attn1 * attn1 * extrapolate(xsb + 1, ysb + 0, dx1, dy1)
  File "/home/lmas/code/opensimplex/opensimplex/opensimplex.py", line 105, in _extrapolate2d
    index = perm[(perm[xsb & 0xFF] + ysb) & 0xFF] & 0x0E
TypeError: unsupported operand type(s) for &: 'float' and 'int'

```

Traced it back to `xsb/ysb` turning into floats after a call to that new `floor()` function.

I've been away from python for too long, you think it's safe/performant to just wrap the `floor()` calls inside an `int(floor(..))`?

**Comment by CreamyCookie** [comment]
@lmas Ah, no problem. =)

Cool that you added tests! Didn't even check Python 2. Oops. I've added a check for Python 2 that wraps `floor` as you suggested.

**Comment by lmas** [comment]
Looks great :+1: 
Also made a simple benchmark, the results from it (for both python 2 and 3) didn't indicate any really performance loss/gain so I think we're pretty good.

Thanks a bunch, pal

**Comment by lmas** [comment]
dammit, wrong button.

**Pull request merged**
