### PR TITLE
Updating _noise2a and _noise4a to output multidimensional arrays

### PR DESCRIPTION
**Pull request by DanielShrimpton**
Updating the _noise2a and _noise4a (noticed another pull request for _noise3a so have omitted in this) functions to output a multidimensional array. Given the inputs are numpy arrays of indices/coordinates then it will iterate over them, constructing a multidimensional array of the generated noise, like in the example code supplied in the repo. Have also added some docstrings and typehints in the functions.

### CODE REVIEW

**Comment by lmas** [comment]
Hi thank you for this.
Would you mind remove the docstring from the _noiseXarray funcs? They're not ment to be used directly so it's just confusing letting them have docstrings.

**Comment by DanielShrimpton** [comment]
Hi no worries, just to confirm, do you mean to remove the docstring from the functions in the class (noiseXarray) or the private ones in the file that the class functions point to (_noiseXa)?

**Comment by lmas** [comment]
Whoops misstyped. Only the private ones (_noiseXa).

-- 
Alex

**Comment by DanielShrimpton** [comment]
I have removed the docstrings from the private functions :)

**Comment by lmas** [comment]
Nice thanks man.
Holding off pulling for now, need to wait for a reply on the other PR.

-- 
Alex

**Comment by DanielShrimpton** [comment]
Sure thing, no worries at all

**Pull request merged**
